### ISSUE TITLE
Performance of decode hook

### ISSUE THREAD

**Issue by Succo** [go-viper/mapstructure#30]
Hello, thanks for having taken the time of forking https://github.com/mitchellh/mapstructure/ 

When using the original project noticed the dynamic decode hook was an expensive part of decoding due to it using reflect on the hook on each pass. Which can happens a lot due as soon as you have slices or nested struct.

I had opened this PR https://github.com/mitchellh/mapstructure/pull/324 to pre compute the hook to typed method.

I think it would be easy to port to the fork, is that something that would interest you ? (In which case I would be interested in helping :smile: ) 

Fabrice

**Comment by sagikazarmark** [comment]
Apologies for the late answer (vacations and all).

Looks like someone already ported this from the original repo: #33

I'm inclined to accept it.
