### ISSUE TITLE
DecodeHook for url.URL

### ISSUE THREAD

**Issue by weeco** [go-viper/mapstructure#31]
Hello,
I'd like to add a decode hook for parsing `url.URL`. Would you accept a PR for it?

**Comment by Vero7979** [comment]
> Hello,
> 
> I'd like to add a decode hook for parsing `url.URL`. Would you accept a PR for it?

 I need to the url crypto is asking

**Comment by sagikazarmark** [comment]
@weeco I'd be happy to accept a PR.

**Comment by einzigartigerName** [comment]
I created a PR implementing this #41
