### ISSUE TITLE
Allow DecodeHook to run for zero values

### ISSUE THREAD

**Issue by yurishkuro** [go-viper/mapstructure#37]
**Use Case**

In the OpenTelemetry Collector we support a configuration like this:
```yaml
receiver:
  http:
  grpc:
```
Here the `http:` entry has no fields, but its presence indicate that the user wants an HTTP server, with all standard defaults. If `http:` is missing than this server will not be started.

**Problem**
Today we're handling it with a custom hook for the `receiver:` which catches the scenario and applies the defaults. The hook is brittle as it depends on the exact YAML field name.

We've been [experimenting with a custom "Optional" type](https://github.com/open-telemetry/opentelemetry-collector/pull/10260/) that would allow to express this much cleaner:
```go
type ReceiverConfig struct {
  HTTP optional.Optional[HTTPServerConfig] `mapstructure:"http"`
}

func DefaultConfig() *ReceiverConfig {
  return &ReceiverConfig{
    HTTP: optional.WithDefault(defaultHTTPConfig), // passing a function
  }
}

func defaultHTTPConfig() HTTPServerConfig { ... }
```
Here `optional.WithDefault` returns `Optional` that has no value, but if during unmarshaling it sees that there was a corresponding entry it first creates default value and then runs normal unmarshal on it.

The issue is that this approach doesn't work today because when `mapstructure` sees an empty value `http:` it just exists, without running the decode hook (which could've made the result non-empty). https://github.com/go-viper/mapstructure/blob/0382e5b7e3987443c91311b7fdb60b92c69a47bf/mapstructure.go#L442-L453

**Proposal**

Could we add another config flag to allow not bailing early on empty values, at least to allow decoder hooks to run?

**Comment by yurishkuro** [comment]
Any feedback from maintainers? Will you accept a PR implementing the proposal?

**Comment by sagikazarmark** [comment]
Hey @yurishkuro!

I think your proposal makes sense. I'd be happy to accept a PR.

**Comment by mahadzaryab1** [comment]
@sagikazarmark The PR is ready for review at https://github.com/go-viper/mapstructure/pull/42. Thank you so much!

**Comment by mahadzaryab1** [comment]
hey @sagikazarmark! just wanted to follow up and ask if it'd be possible to get a review on #42 ?

**Comment by sagikazarmark** [comment]
Thanks for the ping! I'll take a look.

**Comment by mahadzaryab1** [comment]
> Thanks for the ping! I'll take a look.

Thank you so much!

**Comment by yurishkuro** [comment]
@sagikazarmark @mahadzaryab1 turns out the latest fix is still not enough. I tracked the issue to a transformation reproduced here https://go.dev/play/p/byXvFSo01nk. Basically, the hooks have a fundamental design issue that they do not tolerate `nil` (not for long). Even if you start with a typed `nil` represented by `reflect.Value`, the hooks API allows them to accept `reflect.Value` but requires to return the actual value, which most of them do via `v.Interface()`. As the playground example above illustrates it is actually possible to start with a typed `nil` and end up with a real `nil`, which then breaks the chain because it can no longer be converted to `reflect.Value` and back to value via `.Interface()` (the latter panics).

What we have in OTEL Collector is a half-dozen long chain combined into a Composite hook where this transformation from value to `reflect.Value` and back to value happens repeatedly and at some point panics.

One option I see out of that is by introducing the ultimate 4th signature for the hook function that does not force it to drop into the value space:
```
// existing 3rd signature - returns actual value
type DecodeHookFuncValue func(from reflect.Value, to reflect.Value) (interface{}, error)

// ultimate 4th signature - returns reflect.Value
type DecodeHookFuncUltimate func(from reflect.Value, to reflect.Value) (reflect.Value, error)
```

All previous signatures can be reduced to this one as they are special cases. However, in order to achieve `DecodeNil` functionality only the hooks of the ultimate signature can be used safely, while other signatures might panic at some point (which is ok because `DecodeNil` capability is opt-in). I would rewrite OTEL's hooks to all be of the ultimate signature, so that when they don't want to do anything with `from`/`to` values they can just return `from` as is.

This is not a trivial change so would like to run it by here for a stink test.

**Comment by mahadzaryab1** [comment]
> @sagikazarmark @mahadzaryab1 turns out the latest fix is still not enough. I tracked the issue to the transition captured in the following log statements (where `internal.Config` is an alias for `any`):
> 
> ```
> calling hook with: internal.Config(nil)
> hook returned: <nil> or as value <invalid reflect.Value>
> ```
> 
> This transformation reproduced here https://go.dev/play/p/byXvFSo01nk. Basically, the hooks have a fundamental design issue that they do not tolerate `nil` (not for long). Even if you start with a typed `nil` represented by `reflect.Value` (which was done in #45), the hooks API allows them to accept `reflect.Value` but requires to return the actual value, which most of them do via `v.Interface()`. As the playground example above illustrates it is actually possible to start with a typed `nil` and end up with a real `nil`, which then breaks the chain because it can no longer be converted to `reflect.Value` and back to value via `.Interface()` (the latter panics).
> 
> What we have in OTEL Collector is a half-dozen long chain combined into a Composite hook where this transformation from value to `reflect.Value` and back to value happens repeatedly and at some point panics.
> 
> One option I see out of that is by introducing the ultimate 4th signature for the hook function that does not force it to drop into the value space:
> 
> ```
> // existing 3rd signature - returns actual value
> type DecodeHookFuncValue func(from reflect.Value, to reflect.Value) (interface{}, error)
> 
> // ultimate 4th signature - returns reflect.Value
> type DecodeHookFuncUltimate func(from reflect.Value, to reflect.Value) (reflect.Value, error)
> ```
> 
> All previous signatures can be reduced to this one as they are special cases. However, in order to achieve `DecodeNil` functionality only the hooks of the ultimate signature can be used safely, while other signatures might panic at some point (which is ok because `DecodeNil` capability is opt-in). I would rewrite OTEL's hooks to all be of the ultimate signature, so that when they don't want to do anything with `from`/`to` values they can just return `from` as is.
> 
> This is not a trivial change so would like to run it by here for a stink test.

This looks great to me! Let me know if you need help in landing the patch in mapstructure for adding the new decode hook function signature.

**Comment by sagikazarmark** [comment]
@yurishkuro, apologies; I forgot to reply here.

If I understand correctly, you propose adding a 4th type of decode hook that would become standard internal signature (currently being converted [here](https://github.com/go-viper/mapstructure/blob/0b972d9949e7d38156eeb175a5cb48d869e88852/decode_hooks.go#L43-L62)).

Am I correct?

Although it may come with a minor performance hit (would be nice to see how much), I don't think we need to change any of the existing hooks (which would be a massive BC break anyway).

But that also means you need to reimplement all of the hooks you want to use in OTEL (or we do that here with different names or something).

In any case, I think those are two separate issues. We can tackle the first one and figure out what to do with the second later. Maybe we can tag a v3 if necessary.

WDYT? Are you open to sending a PR?

**Comment by yurishkuro** [comment]
Thanks @sagikazarmark - since you're ok with the direction of introducing the "ultimate" hook signature, @mahadzaryab1 and I can work on a prototype. I don't expect any performance hit from this change because internally the framework already treats hooks as if they can get and return `reflect.Value`, but when users supplies more specific hook signatures the code just subtypes them (e.g. by passing `val.Type()` instead of `val`). So in theory the new hook will actually be faster, and not worse.

I expect this change to be fully backwards compatible, it's just a new flavor of the hook that does not require additional wrappers from the framework. Yes, we will need to change OTEL's hooks to the new all-Value signature in order to get to the original desired functionality, but that's not a problem.

**Comment by yurishkuro** [comment]
I just realized that we might be able to get the same functionality without a new hook signature, just by changing this line https://github.com/go-viper/mapstructure/blob/0b972d9949e7d38156eeb175a5cb48d869e88852/decode_hooks.go#L103

Instead of doing unconditional `ValueOf` it can first check if the `data` is already reflect.Value. The existing hooks can just start returning `reflect.Value` instead of `val.Interface()`. I will try this one when I get some free time.

**Comment by mahadzaryab1** [comment]
@yurishkuro I can try giving this a shot. When you say the existing hooks can just return `reflect.Value`, are you talking about the hooks in OTEL?
